window.TIPOVACKA_DATA = {
  "title": "Mundial Tipovačka 2026",
  "timezoneLabel": "CET/CEST",
  "sourceWorkbook": "MS2026_v4_CET_separate.xlsx",
  "generatedFrom": "Game Board / CET Schedule",
  "scoring": {
    "groupExact": 6,
    "groupGoalDifference": 4,
    "groupResult": 2,
    "knockoutMultiplier": 2,
    "groupWinner": 5,
    "champion": 40,
    "runnerUp": 25,
    "thirdPlace": 15,
    "bestPlayer": 15,
    "topScorer": 15,
    "bestYoung": 15,
    "bestGoalkeeper": 15,
    "bestCzechScorer": 10
  },
  "players": [
    {
      "name": "Marťa",
      "pin": "1111"
    },
    {
      "name": "Míša",
      "pin": "2222"
    },
    {
      "name": "Honzík",
      "pin": "3333"
    },
    {
      "name": "Stáník",
      "pin": "4444"
    }
  ],
  "groups": {
    "A": [
      "Mexico",
      "South Africa",
      "South Korea",
      "Czech Republic"
    ],
    "B": [
      "Canada",
      "Bosnia and Herzegovina",
      "Qatar",
      "Switzerland"
    ],
    "C": [
      "Brazil",
      "Morocco",
      "Haiti",
      "Scotland"
    ],
    "D": [
      "United States",
      "Paraguay",
      "Australia",
      "Turkey"
    ],
    "E": [
      "Germany",
      "Curaçao",
      "Ivory Coast",
      "Ecuador"
    ],
    "F": [
      "Netherlands",
      "Japan",
      "Sweden",
      "Tunisia"
    ],
    "G": [
      "Belgium",
      "Egypt",
      "Iran",
      "New Zealand"
    ],
    "H": [
      "Spain",
      "Cape Verde",
      "Saudi Arabia",
      "Uruguay"
    ],
    "I": [
      "France",
      "Senegal",
      "Iraq",
      "Norway"
    ],
    "J": [
      "Argentina",
      "Algeria",
      "Austria",
      "Jordan"
    ],
    "K": [
      "Portugal",
      "DR Congo",
      "Uzbekistan",
      "Colombia"
    ],
    "L": [
      "England",
      "Croatia",
      "Ghana",
      "Panama"
    ]
  },
  "flags": {
    "Mexico": "🇲🇽",
    "South Africa": "🇿🇦",
    "South Korea": "🇰🇷",
    "Czech Republic": "🇨🇿",
    "Canada": "🇨🇦",
    "Bosnia and Herzegovina": "🇧🇦",
    "Qatar": "🇶🇦",
    "Switzerland": "🇨🇭",
    "Brazil": "🇧🇷",
    "Morocco": "🇲🇦",
    "Haiti": "🇭🇹",
    "Scotland": "🏴",
    "United States": "🇺🇸",
    "Paraguay": "🇵🇾",
    "Australia": "🇦🇺",
    "Turkey": "🇹🇷",
    "Germany": "🇩🇪",
    "Curaçao": "🇨🇼",
    "Ivory Coast": "🇨🇮",
    "Ecuador": "🇪🇨",
    "Netherlands": "🇳🇱",
    "Japan": "🇯🇵",
    "Sweden": "🇸🇪",
    "Tunisia": "🇹🇳",
    "Belgium": "🇧🇪",
    "Egypt": "🇪🇬",
    "Iran": "🇮🇷",
    "New Zealand": "🇳🇿",
    "Spain": "🇪🇸",
    "Cape Verde": "🇨🇻",
    "Saudi Arabia": "🇸🇦",
    "Uruguay": "🇺🇾",
    "France": "🇫🇷",
    "Senegal": "🇸🇳",
    "Iraq": "🇮🇶",
    "Norway": "🇳🇴",
    "Argentina": "🇦🇷",
    "Algeria": "🇩🇿",
    "Austria": "🇦🇹",
    "Jordan": "🇯🇴",
    "Portugal": "🇵🇹",
    "DR Congo": "🇨🇩",
    "Uzbekistan": "🇺🇿",
    "Colombia": "🇨🇴",
    "England": "🏴",
    "Croatia": "🇭🇷",
    "Ghana": "🇬🇭",
    "Panama": "🇵🇦"
  },
  "matches": [
    {
      "id": 1,
      "round": "Group A",
      "stage": "Group",
      "group": "A",
      "date": "2026-06-11",
      "time": "21:00",
      "home": "Mexico",
      "away": "South Africa",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 2,
      "round": "Group A",
      "stage": "Group",
      "group": "A",
      "date": "2026-06-12",
      "time": "04:00",
      "home": "South Korea",
      "away": "Czech Republic",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 3,
      "round": "Group B",
      "stage": "Group",
      "group": "B",
      "date": "2026-06-12",
      "time": "21:00",
      "home": "Canada",
      "away": "Bosnia and Herzegovina",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 4,
      "round": "Group D",
      "stage": "Group",
      "group": "D",
      "date": "2026-06-13",
      "time": "03:00",
      "home": "United States",
      "away": "Paraguay",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 5,
      "round": "Group C",
      "stage": "Group",
      "group": "C",
      "date": "2026-06-14",
      "time": "03:00",
      "home": "Haiti",
      "away": "Scotland",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 6,
      "round": "Group D",
      "stage": "Group",
      "group": "D",
      "date": "2026-06-14",
      "time": "06:00",
      "home": "Australia",
      "away": "Turkey",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 7,
      "round": "Group C",
      "stage": "Group",
      "group": "C",
      "date": "2026-06-14",
      "time": "00:00",
      "home": "Brazil",
      "away": "Morocco",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 8,
      "round": "Group B",
      "stage": "Group",
      "group": "B",
      "date": "2026-06-13",
      "time": "21:00",
      "home": "Qatar",
      "away": "Switzerland",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 9,
      "round": "Group E",
      "stage": "Group",
      "group": "E",
      "date": "2026-06-15",
      "time": "01:00",
      "home": "Ivory Coast",
      "away": "Ecuador",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 10,
      "round": "Group E",
      "stage": "Group",
      "group": "E",
      "date": "2026-06-14",
      "time": "19:00",
      "home": "Germany",
      "away": "Curaçao",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 11,
      "round": "Group F",
      "stage": "Group",
      "group": "F",
      "date": "2026-06-14",
      "time": "22:00",
      "home": "Netherlands",
      "away": "Japan",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 12,
      "round": "Group F",
      "stage": "Group",
      "group": "F",
      "date": "2026-06-15",
      "time": "04:00",
      "home": "Sweden",
      "away": "Tunisia",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 13,
      "round": "Group H",
      "stage": "Group",
      "group": "H",
      "date": "2026-06-16",
      "time": "00:00",
      "home": "Saudi Arabia",
      "away": "Uruguay",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 14,
      "round": "Group H",
      "stage": "Group",
      "group": "H",
      "date": "2026-06-15",
      "time": "18:00",
      "home": "Spain",
      "away": "Cape Verde",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 15,
      "round": "Group G",
      "stage": "Group",
      "group": "G",
      "date": "2026-06-16",
      "time": "03:00",
      "home": "Iran",
      "away": "New Zealand",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 16,
      "round": "Group G",
      "stage": "Group",
      "group": "G",
      "date": "2026-06-15",
      "time": "21:00",
      "home": "Belgium",
      "away": "Egypt",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 17,
      "round": "Group I",
      "stage": "Group",
      "group": "I",
      "date": "2026-06-16",
      "time": "21:00",
      "home": "France",
      "away": "Senegal",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 18,
      "round": "Group I",
      "stage": "Group",
      "group": "I",
      "date": "2026-06-17",
      "time": "00:00",
      "home": "Iraq",
      "away": "Norway",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 19,
      "round": "Group J",
      "stage": "Group",
      "group": "J",
      "date": "2026-06-17",
      "time": "03:00",
      "home": "Argentina",
      "away": "Algeria",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 20,
      "round": "Group J",
      "stage": "Group",
      "group": "J",
      "date": "2026-06-17",
      "time": "06:00",
      "home": "Austria",
      "away": "Jordan",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 21,
      "round": "Group L",
      "stage": "Group",
      "group": "L",
      "date": "2026-06-18",
      "time": "01:00",
      "home": "Ghana",
      "away": "Panama",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 22,
      "round": "Group L",
      "stage": "Group",
      "group": "L",
      "date": "2026-06-17",
      "time": "22:00",
      "home": "England",
      "away": "Croatia",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 23,
      "round": "Group K",
      "stage": "Group",
      "group": "K",
      "date": "2026-06-17",
      "time": "19:00",
      "home": "Portugal",
      "away": "DR Congo",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 24,
      "round": "Group K",
      "stage": "Group",
      "group": "K",
      "date": "2026-06-18",
      "time": "04:00",
      "home": "Uzbekistan",
      "away": "Colombia",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 25,
      "round": "Group A",
      "stage": "Group",
      "group": "A",
      "date": "2026-06-18",
      "time": "18:00",
      "home": "Czech Republic",
      "away": "South Africa",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 26,
      "round": "Group B",
      "stage": "Group",
      "group": "B",
      "date": "2026-06-18",
      "time": "21:00",
      "home": "Switzerland",
      "away": "Bosnia and Herzegovina",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 27,
      "round": "Group B",
      "stage": "Group",
      "group": "B",
      "date": "2026-06-19",
      "time": "00:00",
      "home": "Canada",
      "away": "Qatar",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 28,
      "round": "Group A",
      "stage": "Group",
      "group": "A",
      "date": "2026-06-19",
      "time": "03:00",
      "home": "Mexico",
      "away": "South Korea",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 29,
      "round": "Group C",
      "stage": "Group",
      "group": "C",
      "date": "2026-06-20",
      "time": "02:30",
      "home": "Brazil",
      "away": "Haiti",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 30,
      "round": "Group C",
      "stage": "Group",
      "group": "C",
      "date": "2026-06-20",
      "time": "00:00",
      "home": "Scotland",
      "away": "Morocco",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 31,
      "round": "Group D",
      "stage": "Group",
      "group": "D",
      "date": "2026-06-20",
      "time": "05:00",
      "home": "Turkey",
      "away": "Paraguay",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 32,
      "round": "Group D",
      "stage": "Group",
      "group": "D",
      "date": "2026-06-19",
      "time": "21:00",
      "home": "United States",
      "away": "Australia",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 33,
      "round": "Group E",
      "stage": "Group",
      "group": "E",
      "date": "2026-06-20",
      "time": "22:00",
      "home": "Germany",
      "away": "Ivory Coast",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 34,
      "round": "Group E",
      "stage": "Group",
      "group": "E",
      "date": "2026-06-21",
      "time": "02:00",
      "home": "Ecuador",
      "away": "Curaçao",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 35,
      "round": "Group F",
      "stage": "Group",
      "group": "F",
      "date": "2026-06-20",
      "time": "19:00",
      "home": "Netherlands",
      "away": "Sweden",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 36,
      "round": "Group F",
      "stage": "Group",
      "group": "F",
      "date": "2026-06-21",
      "time": "06:00",
      "home": "Tunisia",
      "away": "Japan",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 37,
      "round": "Group H",
      "stage": "Group",
      "group": "H",
      "date": "2026-06-22",
      "time": "00:00",
      "home": "Uruguay",
      "away": "Cape Verde",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 38,
      "round": "Group H",
      "stage": "Group",
      "group": "H",
      "date": "2026-06-21",
      "time": "18:00",
      "home": "Spain",
      "away": "Saudi Arabia",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 39,
      "round": "Group G",
      "stage": "Group",
      "group": "G",
      "date": "2026-06-21",
      "time": "21:00",
      "home": "Belgium",
      "away": "Iran",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 40,
      "round": "Group G",
      "stage": "Group",
      "group": "G",
      "date": "2026-06-22",
      "time": "03:00",
      "home": "New Zealand",
      "away": "Egypt",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 41,
      "round": "Group I",
      "stage": "Group",
      "group": "I",
      "date": "2026-06-23",
      "time": "02:00",
      "home": "Norway",
      "away": "Senegal",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 42,
      "round": "Group I",
      "stage": "Group",
      "group": "I",
      "date": "2026-06-22",
      "time": "23:00",
      "home": "France",
      "away": "Iraq",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 43,
      "round": "Group J",
      "stage": "Group",
      "group": "J",
      "date": "2026-06-22",
      "time": "19:00",
      "home": "Argentina",
      "away": "Austria",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 44,
      "round": "Group J",
      "stage": "Group",
      "group": "J",
      "date": "2026-06-23",
      "time": "05:00",
      "home": "Jordan",
      "away": "Algeria",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 45,
      "round": "Group L",
      "stage": "Group",
      "group": "L",
      "date": "2026-06-23",
      "time": "22:00",
      "home": "England",
      "away": "Ghana",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 46,
      "round": "Group L",
      "stage": "Group",
      "group": "L",
      "date": "2026-06-24",
      "time": "01:00",
      "home": "Panama",
      "away": "Croatia",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 47,
      "round": "Group K",
      "stage": "Group",
      "group": "K",
      "date": "2026-06-23",
      "time": "19:00",
      "home": "Portugal",
      "away": "Uzbekistan",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 48,
      "round": "Group K",
      "stage": "Group",
      "group": "K",
      "date": "2026-06-24",
      "time": "04:00",
      "home": "Colombia",
      "away": "DR Congo",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 49,
      "round": "Group C",
      "stage": "Group",
      "group": "C",
      "date": "2026-06-25",
      "time": "00:00",
      "home": "Scotland",
      "away": "Brazil",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 50,
      "round": "Group C",
      "stage": "Group",
      "group": "C",
      "date": "2026-06-25",
      "time": "00:00",
      "home": "Morocco",
      "away": "Haiti",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 51,
      "round": "Group B",
      "stage": "Group",
      "group": "B",
      "date": "2026-06-24",
      "time": "21:00",
      "home": "Switzerland",
      "away": "Canada",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 52,
      "round": "Group B",
      "stage": "Group",
      "group": "B",
      "date": "2026-06-24",
      "time": "21:00",
      "home": "Bosnia and Herzegovina",
      "away": "Qatar",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 53,
      "round": "Group A",
      "stage": "Group",
      "group": "A",
      "date": "2026-06-25",
      "time": "03:00",
      "home": "Czech Republic",
      "away": "Mexico",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 54,
      "round": "Group A",
      "stage": "Group",
      "group": "A",
      "date": "2026-06-25",
      "time": "03:00",
      "home": "South Africa",
      "away": "South Korea",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 55,
      "round": "Group E",
      "stage": "Group",
      "group": "E",
      "date": "2026-06-25",
      "time": "22:00",
      "home": "Curaçao",
      "away": "Ivory Coast",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 56,
      "round": "Group E",
      "stage": "Group",
      "group": "E",
      "date": "2026-06-25",
      "time": "22:00",
      "home": "Ecuador",
      "away": "Germany",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 57,
      "round": "Group F",
      "stage": "Group",
      "group": "F",
      "date": "2026-06-26",
      "time": "01:00",
      "home": "Japan",
      "away": "Sweden",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 58,
      "round": "Group F",
      "stage": "Group",
      "group": "F",
      "date": "2026-06-26",
      "time": "01:00",
      "home": "Tunisia",
      "away": "Netherlands",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 59,
      "round": "Group D",
      "stage": "Group",
      "group": "D",
      "date": "2026-06-26",
      "time": "04:00",
      "home": "Turkey",
      "away": "United States",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 60,
      "round": "Group D",
      "stage": "Group",
      "group": "D",
      "date": "2026-06-26",
      "time": "04:00",
      "home": "Paraguay",
      "away": "Australia",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 61,
      "round": "Group I",
      "stage": "Group",
      "group": "I",
      "date": "2026-06-26",
      "time": "21:00",
      "home": "Norway",
      "away": "France",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 62,
      "round": "Group I",
      "stage": "Group",
      "group": "I",
      "date": "2026-06-26",
      "time": "21:00",
      "home": "Senegal",
      "away": "Iraq",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 63,
      "round": "Group G",
      "stage": "Group",
      "group": "G",
      "date": "2026-06-27",
      "time": "05:00",
      "home": "Egypt",
      "away": "Iran",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 64,
      "round": "Group G",
      "stage": "Group",
      "group": "G",
      "date": "2026-06-27",
      "time": "05:00",
      "home": "New Zealand",
      "away": "Belgium",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 65,
      "round": "Group H",
      "stage": "Group",
      "group": "H",
      "date": "2026-06-27",
      "time": "02:00",
      "home": "Cape Verde",
      "away": "Saudi Arabia",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 66,
      "round": "Group H",
      "stage": "Group",
      "group": "H",
      "date": "2026-06-27",
      "time": "02:00",
      "home": "Uruguay",
      "away": "Spain",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 67,
      "round": "Group L",
      "stage": "Group",
      "group": "L",
      "date": "2026-06-27",
      "time": "23:00",
      "home": "Panama",
      "away": "England",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 68,
      "round": "Group L",
      "stage": "Group",
      "group": "L",
      "date": "2026-06-27",
      "time": "23:00",
      "home": "Croatia",
      "away": "Ghana",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 69,
      "round": "Group J",
      "stage": "Group",
      "group": "J",
      "date": "2026-06-28",
      "time": "04:00",
      "home": "Algeria",
      "away": "Austria",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 70,
      "round": "Group J",
      "stage": "Group",
      "group": "J",
      "date": "2026-06-28",
      "time": "04:00",
      "home": "Jordan",
      "away": "Argentina",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 71,
      "round": "Group K",
      "stage": "Group",
      "group": "K",
      "date": "2026-06-28",
      "time": "01:30",
      "home": "Colombia",
      "away": "Portugal",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 72,
      "round": "Group K",
      "stage": "Group",
      "group": "K",
      "date": "2026-06-28",
      "time": "01:30",
      "home": "DR Congo",
      "away": "Uzbekistan",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 73,
      "round": "R32",
      "stage": "Knockout",
      "group": "R32",
      "date": "2026-06-28",
      "time": "21:00",
      "home": "Runner-up Group A",
      "away": "Runner-up Group B",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 74,
      "round": "R32",
      "stage": "Knockout",
      "group": "R32",
      "date": "2026-06-29",
      "time": "22:30",
      "home": "Winner Group E",
      "away": "3rd Group A/B/C/D/F",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 75,
      "round": "R32",
      "stage": "Knockout",
      "group": "R32",
      "date": "2026-06-30",
      "time": "03:00",
      "home": "Winner Group F",
      "away": "Runner-up Group C",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 76,
      "round": "R32",
      "stage": "Knockout",
      "group": "R32",
      "date": "2026-06-29",
      "time": "19:00",
      "home": "Winner Group C",
      "away": "Runner-up Group F",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 77,
      "round": "R32",
      "stage": "Knockout",
      "group": "R32",
      "date": "2026-06-30",
      "time": "23:00",
      "home": "Winner Group I",
      "away": "3rd Group C/D/F/G/H",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 78,
      "round": "R32",
      "stage": "Knockout",
      "group": "R32",
      "date": "2026-06-30",
      "time": "19:00",
      "home": "Runner-up Group E",
      "away": "Runner-up Group I",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 79,
      "round": "R32",
      "stage": "Knockout",
      "group": "R32",
      "date": "2026-07-01",
      "time": "03:00",
      "home": "Winner Group A",
      "away": "3rd Group C/E/F/H/I",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 80,
      "round": "R32",
      "stage": "Knockout",
      "group": "R32",
      "date": "2026-07-01",
      "time": "18:00",
      "home": "Winner Group L",
      "away": "3rd Group E/H/I/J/K",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 81,
      "round": "R32",
      "stage": "Knockout",
      "group": "R32",
      "date": "2026-07-02",
      "time": "02:00",
      "home": "Winner Group D",
      "away": "3rd Group B/E/F/I/J",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 82,
      "round": "R32",
      "stage": "Knockout",
      "group": "R32",
      "date": "2026-07-01",
      "time": "22:00",
      "home": "Winner Group G",
      "away": "3rd Group A/E/H/I/J",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 83,
      "round": "R32",
      "stage": "Knockout",
      "group": "R32",
      "date": "2026-07-03",
      "time": "01:00",
      "home": "Runner-up Group K",
      "away": "Runner-up Group L",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 84,
      "round": "R32",
      "stage": "Knockout",
      "group": "R32",
      "date": "2026-07-02",
      "time": "21:00",
      "home": "Winner Group H",
      "away": "Runner-up Group J",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 85,
      "round": "R32",
      "stage": "Knockout",
      "group": "R32",
      "date": "2026-07-03",
      "time": "05:00",
      "home": "Winner Group B",
      "away": "3rd Group E/F/G/I/J",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 86,
      "round": "R32",
      "stage": "Knockout",
      "group": "R32",
      "date": "2026-07-04",
      "time": "00:00",
      "home": "Winner Group J",
      "away": "Runner-up Group H",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 87,
      "round": "R32",
      "stage": "Knockout",
      "group": "R32",
      "date": "2026-07-04",
      "time": "03:30",
      "home": "Winner Group K",
      "away": "3rd Group D/E/I/J/L",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 88,
      "round": "R32",
      "stage": "Knockout",
      "group": "R32",
      "date": "2026-07-03",
      "time": "20:00",
      "home": "Runner-up Group D",
      "away": "Runner-up Group G",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 89,
      "round": "R16",
      "stage": "Knockout",
      "group": "R16",
      "date": "2026-07-04",
      "time": "23:00",
      "home": "Winner Match 74",
      "away": "Winner Match 77",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 90,
      "round": "R16",
      "stage": "Knockout",
      "group": "R16",
      "date": "2026-07-04",
      "time": "19:00",
      "home": "Winner Match 73",
      "away": "Winner Match 75",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 91,
      "round": "R16",
      "stage": "Knockout",
      "group": "R16",
      "date": "2026-07-05",
      "time": "22:00",
      "home": "Winner Match 76",
      "away": "Winner Match 78",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 92,
      "round": "R16",
      "stage": "Knockout",
      "group": "R16",
      "date": "2026-07-06",
      "time": "02:00",
      "home": "Winner Match 79",
      "away": "Winner Match 80",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 93,
      "round": "R16",
      "stage": "Knockout",
      "group": "R16",
      "date": "2026-07-06",
      "time": "21:00",
      "home": "Winner Match 83",
      "away": "Winner Match 84",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 94,
      "round": "R16",
      "stage": "Knockout",
      "group": "R16",
      "date": "2026-07-07",
      "time": "02:00",
      "home": "Winner Match 81",
      "away": "Winner Match 82",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 95,
      "round": "R16",
      "stage": "Knockout",
      "group": "R16",
      "date": "2026-07-07",
      "time": "18:00",
      "home": "Winner Match 86",
      "away": "Winner Match 88",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 96,
      "round": "R16",
      "stage": "Knockout",
      "group": "R16",
      "date": "2026-07-07",
      "time": "22:00",
      "home": "Winner Match 85",
      "away": "Winner Match 87",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 97,
      "round": "QF",
      "stage": "Knockout",
      "group": "QF",
      "date": "2026-07-09",
      "time": "22:00",
      "home": "Winner Match 89",
      "away": "Winner Match 90",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 98,
      "round": "QF",
      "stage": "Knockout",
      "group": "QF",
      "date": "2026-07-10",
      "time": "21:00",
      "home": "Winner Match 93",
      "away": "Winner Match 94",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 99,
      "round": "QF",
      "stage": "Knockout",
      "group": "QF",
      "date": "2026-07-11",
      "time": "23:00",
      "home": "Winner Match 91",
      "away": "Winner Match 92",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 100,
      "round": "QF",
      "stage": "Knockout",
      "group": "QF",
      "date": "2026-07-12",
      "time": "03:00",
      "home": "Winner Match 95",
      "away": "Winner Match 96",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 101,
      "round": "SF",
      "stage": "Knockout",
      "group": "SF",
      "date": "2026-07-14",
      "time": "21:00",
      "home": "Winner Match 97",
      "away": "Winner Match 98",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 102,
      "round": "SF",
      "stage": "Knockout",
      "group": "SF",
      "date": "2026-07-15",
      "time": "21:00",
      "home": "Winner Match 99",
      "away": "Winner Match 100",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 103,
      "round": "3rd",
      "stage": "Knockout",
      "group": "3rd",
      "date": "2026-07-18",
      "time": "23:00",
      "home": "Loser Match 101",
      "away": "Loser Match 102",
      "home_goals": "",
      "away_goals": ""
    },
    {
      "id": 104,
      "round": "Final",
      "stage": "Knockout",
      "group": "Final",
      "date": "2026-07-19",
      "time": "21:00",
      "home": "Winner Match 101",
      "away": "Winner Match 102",
      "home_goals": "",
      "away_goals": ""
    }
  ]
};
